services: 
 csvserver:
  image: infracloudio/csvserver:latest
  container_name: csvserver
  environment:
    CSVSERVER_BORDER: "Orange"
  volumes:
    - "./inputFile:/csvserver/inputdata:rw"
  ports:
    - "9393:9300"
  restart: unless-stopped
  networks:
    - my-network-name
  

 prometheus:
  image: prom/prometheus:v2.30.3
  container_name: prometheus
  privileged: true
  volumes:
    - prometheus_data:/prometheus 
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./alert.rules:/etc/prometheus/alert.rules
  command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - '--storage.tsdb.path=/prometheus'
  ports:
    - "9090:9090"
  restart: unless-stopped
  networks:
    - my-network-name


volumes:
  prometheus_data: {}

networks:
  my-network-name:
    name: test-csvserver