###Web Server Installation

FROM ubuntu:latest
RUN  apt-get update && apt-get install -y \
     apache2 \
     apache2-utils \
     python-pip \
     git \
     wget 

RUN  pip install --upgrade pip \
     && pip install PyMySQL \
     && git clone https://gitlab.com/crest1/devops_test.git \
     && cd devops_test/ \
     chmod +x install.sh

RUN a2dismod mpm_event && a2enmod mpm_prefork 
    
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_RUN_DIR /var/www/html

COPY .000-default.conf /etc/apache2/sites-enabled/
COPY .ports.conf /etc/apache2/

ENTRYPOINT ["/usr/sbin/apache2"]
CMD ["-D", "FOREGROUND"]

EXPOSE 80
