version: "2"

networks:
  compose_network:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 10.5.0.0/16
    #       gateway: 10.5.0.1      

services:
  app_server:
    build: .
    # image: nginx-crest-app:latest
    container_name: app_server
    links:
      - mysql_server
    ports:
      - "80:80"
    restart: unless-stopped
    # volumes:
    #   - .000-default.conf:/etc/apache2/sites-enabled/:rw
    #   - .ports.conf:/etc/apache2/:rw
    dns:
      - appserver.company.com
    networks:
      - compose_network   
    # networks:
    #   compose_network:
    #     ipv4_address: 10.5.0.5

  web_server:
    build: .
    # image: nginx-crest-web:latest
    container_name: web_server
    depends_on:
      - mysql_server
    ports:
      - "8081:8080"
    restart: unless-stopped
    # volumes:
    #   - .000-default.conf:/etc/apache2/sites-enabled/:rw
    #   - .ports.conf:/etc/apache2/:rw
    networks: 
      - compose_network

  mysql_server:
    build: .
    container_name: mysql_server
    # image: mysql-crest:latest
    environment:
      MYSQL_ROOT_PASSWORD: crestapp123
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"
    volumes:
      - ./sql/create_db_table.sql:/sql:rw
    restart: unless-stopped
    dns:
      - dbserver.company.com
    networks: 
    - compose_network
