########### Configure Default Memory Requests and Limits for a Namespace


#### Create a LimitRange and a Pod.
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container


# ### Now if you create a Pod in the default-mem-example namespace, and any container within that Pod does not specify its own values for memory request and memory limit, then the control plane applies default values: a memory request of 256MiB and a memory limit of 512MiB.
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: default-mem-demo
# spec:
#   containers:
#   - name: default-mem-demo-ctr
#     image: nginx


---
apiVersion: v1
kind: Pod
metadata:
  name: default-mem-demo-2
spec:
  containers:
  - name: default-mem-demo-2-ctr
    image: nginx
    resources:
      limits:
        memory: "1Gi"
