apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:   
        - name: nodejs
          image: dhirendrabyte/node-server:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 0.5Gi
      imagePullSecrets:
        - name: dockerhub-cred  
